### ISSUE TITLE
Supervised hassio: No module named 'pyudev

### ISSUE THREAD

**Issue by LudoOne** [tikismoke/home-assistant-plcbus#3]
When started the module logs an error stating:
Platform error switch.plcbus - No module named 'pyudev

**Comment by tikismoke** [comment]
Surely need to modify the requirements needed.

**Comment by tikismoke** [comment]
Have you been able to made plcbus works or not at all?

**Comment by tikismoke** [comment]
I'm surprised pyudev is already in the requirements part. It should have been installed automatically.

**Comment by LudoOne** [comment]
> 
> 
> Have you been able to made plcbus works or not at all?

I'm following https://developers.home-assistant.io/docs/creating_integration_manifest by putting https://github.com/pyudev/pyudev/tree/develop-0.22/src/pyudev into /config/deps, reboot, but no avail

**Comment by tikismoke** [comment]
What about pip install it by hand like here:

https://developers.home-assistant.io/docs/creating_integration_manifest/#custom-requirements-during-development--testing

**Comment by LudoOne** [comment]
> 
> 
> What about pip install it by hand like here:
> 
> https://developers.home-assistant.io/docs/creating_integration_manifest/#custom-requirements-during-development--testing

Did a pip install pyudev inside the console of the homeassistant container:

bash-5.0# pip install pyudev
Requirement already satisfied: pyudev in /usr/local/lib/python3.7/site-packages (0.22.0)
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from pyudev) (1.15.0)

**Comment by tikismoke** [comment]
:( how could it be already installed and not available...

I'm running hass on a dedicated vm not supervised I have to look at the difference but it should work.

Will look at it tomorrow.

Le 20 juin 2020 23:43:42 GMT+02:00, LudoOne <notifications@github.com> a écrit :
>> 
>> 
>> What about pip install it by hand like here:
>> 
>>
>https://developers.home-assistant.io/docs/creating_integration_manifest/#custom-requirements-during-development--testing
>
>Did a pip install pyudev inside the console of the homeassistant
>container:
>
>bash-5.0# pip install pyudev
>Requirement already satisfied: pyudev in
>/usr/local/lib/python3.7/site-packages (0.22.0)
>Requirement already satisfied: six in
>/usr/local/lib/python3.7/site-packages (from pyudev) (1.15.0)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/tikismoke/home-assistant-plcbus/issues/3#issuecomment-647048658

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

Attention nous avons changer de domaine, utilisez poudot.fr à la place de tikijs.dyndns.org

**Comment by LudoOne** [comment]
I think it needed some (host) reboots? The integration is now loaded. 

It is logging a Warning: SwitchDevice is deprecated, modify PlcbusSwitch to extend SwitchEntity.
On HA 0.111.4

**Comment by tikismoke** [comment]
I also have an issue some times when serial disappeare from vm and ad also to restart the vm(not the host in my case) completely to get it working back.

**Comment by LudoOne** [comment]
> I also have an issue some times when serial disappeare from vm and ad also to restart the vm(not the host in my case) completely to get it working back.

That one I didn't experience yet. But I'm using an rpi4, so I would blame usb power if I would ever encounter.

**Comment by LudoOne** [comment]
Previously I would use a perl script from https://code.google.com/archive/p/plcbus-daemon-for-linux/wikis/Installation_and_usage.wiki
