### ISSUE TITLE
Info: 'install' is deprecated, use 'async_install' instead.

### ISSUE THREAD

**Issue by LudoOne** [tikismoke/home-assistant-plcbus#4]
After install the following info is logged:
'install' is deprecated, use 'async_install' instead

**Comment by tikismoke** [comment]
> After install the following info is logged:
> 'install' is deprecated, use 'async_install' instead

https://github.com/hacs/integration/issues/1320
This seems related to hacs. It should be closed in hacs parts.
Could you retry and update the issue please?

**Comment by tikismoke** [comment]
Close as it's from HACS side
